import "./globals.css";

import React from "react";
import { AuthProvider } from "@/providers/auth-provider";
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import Navigation from "./components/navigation/Navigation";
import Footer from "./components/footer/Footer";
import ReduxProvider from "../providers/redux-provider";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <ReduxProvider>
        <html lang="en">
          <body className={poppins.className}>
            <Navigation />
            {children}
            <Footer />
          </body>
        </html>
      </ReduxProvider>
    </AuthProvider>
  );
}
